export const Genres = [
  ['80s', '80s'],
  ['Chill', 'chill'],
  ['Disco', 'disco'],
  ['Workout', 'workout'],
  ['Hip-Hop', 'hip-hop'],
  ['K-pop', 'k-pop'],
  ['Drum & Bass', 'drum_n_bass'],
  ['Jazz', 'jazz'],
  ['Country', 'country'],
  ['Romance', 'romance'],
  ['Indie', 'indie'],
  ['Gospel', 'gospel'],
  ['Pop', 'pop'],
  ['Punk', 'punk'],
  ['Metal', 'metal'],
];
