version: '3.9'
services:

  #backend:
  #  build: Dockerfile-backend
  #  container_name: "backend"
  #  ports:
  #    - 8080:8080
  #  expose:
  #    - 8080

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile-frontend-prod
    container_name: "frontend"
    ports:
      - 80:80
    expose:
      - 80