name: CI Tests

on: 
  pull_request:
    branches: [ dev ]

jobs:
  test-frontend:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 16 ]


    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: resolving dependencies
        run: npm i
        working-directory: frontend

      - name: testing
        run: npm run test:prod
        working-directory: frontend

      - name: linter tests
        run: npm run lint
        working-directory: frontend

  test-backend:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 16 ]


    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
        working-directory: backend

      - name: Gradle clean
        run: ./gradlew clean
        working-directory: backend
        env:
          SPRING_PROFILES_ACTIVE: dev

      - name: Gradle Test
        run: ./gradlew test
        working-directory: backend
        env:
          SPRING_PROFILES_ACTIVE: dev