name: Client CI

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - 'backend/**'
      - 'Milestone 1/**'
      - 'Milestone 2/**'
      - 'Milestone 3/**'
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - 'backend/**'
      - 'Milestone 1/**'
      - 'Milestone 2/**'
      - 'Milestone 3/**'


jobs:

  test-client:
    name: Client tests
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: resolving dependencies
        run: npm ci
        working-directory: frontend

      - name: testing
        run: npm run test:prod
        working-directory: frontend

      - name: linter tests
        run: npm run lint
        working-directory: frontend