name: Server CI

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - 'frontend/**'
      - 'Milestone 1/**'
      - 'Milestone 2/**'
      - 'Milestone 3/**'
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - 'frontend/**'
      - 'Milestone 1/**'
      - 'Milestone 2/**'
      - 'Milestone 3/**'


jobs:

  test-server:
    name: Server tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
        working-directory: backend

      - name: Gradle clean
        run: ./gradlew clean
        working-directory: backend
        env:
          SPRING_PROFILES_ACTIVE: dev

      - name: Gradle Test
        run: ./gradlew test --tests "*"
        working-directory: backend
        env:
          SPRING_PROFILES_ACTIVE: dev